blank_issues_enabled: true
contact_links:
  - name: 一键部署到Vercel
    url: https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2FRY-zzcn%2FSubScribe
    about: 点击此链接将SubScribe一键部署到Vercel
  - name: 一键部署到Cloudflare Pages
    url: https://deploy.workers.cloudflare.com/?url=https://github.com/RY-zzcn/SubScribe
    about: 点击此链接将SubScribe一键部署到Cloudflare Pages 