name = "subscribe-api"
main = "worker.js"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]

# KV命名空间配置
[[kv_namespaces]]
binding = "SUBSCRIBE_KV"
id = "your-kv-namespace-id"  # 需要替换为实际的KV命名空间ID

# 环境变量配置
[vars]
ENVIRONMENT = "production"

# 开发环境配置
[env.development]
vars = { ENVIRONMENT = "development" }

# 路由配置
[[routes]]
pattern = "/api/*"
zone_id = "your-zone-id"  # 需要替换为实际的区域ID 